site_name: MVP Doc
nav:
    - MVP Documentation: index.md
    - Getting Started: installation.md
    - PVS Mapping Pipelines: pvs.md
    - PVS Quality Control and Correction: pvs_qc.md 
    - About: about.md
    - Licence: license.md
theme: readthedocs
markdown_extensions:
    - admonition
